version: "3.8"

services:
  tvproxy:
    build: https://github.com/nzo66/tvproxy.git#main
    container_name: tvproxy
    restart: unless-stopped
    ports:
      - '7860:7860'
    environment:
      # =============================================================================
      # CONFIGURAZIONE BASE
      # =============================================================================
      - PORT=7860
      - REQUEST_TIMEOUT=45
      - VERIFY_SSL=false
      
      # =============================================================================
      # CONFIGURAZIONE PROXY OPZIONALE
      # =============================================================================
      - PROXY=
      - DADDY_PROXY=
      - NO_PROXY_DOMAINS=github.com,raw.githubusercontent.com
      
      # =============================================================================
      # CONFIGURAZIONE CACHE
      # =============================================================================
      - CACHE_ENABLED=true
      - CACHE_TTL_M3U8=5
      - CACHE_TTL_TS=600
      - CACHE_TTL_KEY=600
      - CACHE_MAXSIZE_M3U8=500
      - CACHE_MAXSIZE_TS=8000
      - CACHE_MAXSIZE_KEY=1000
      
      # =============================================================================
      # CONFIGURAZIONE PRE-BUFFER
      # =============================================================================
      - PREBUFFER_ENABLED=true
      - PREBUFFER_MAX_SEGMENTS=5
      - PREBUFFER_MAX_SIZE_MB=200
      - PREBUFFER_CLEANUP_INTERVAL=300
      - PREBUFFER_MAX_MEMORY_PERCENT=30.0
      - PREBUFFER_EMERGENCY_THRESHOLD=99.9
      
      # =============================================================================
      # CONFIGURAZIONE CONNESSIONI
      # =============================================================================
      - KEEP_ALIVE_TIMEOUT=900
      - MAX_KEEP_ALIVE_REQUESTS=5000
      - POOL_CONNECTIONS=50
      - POOL_MAXSIZE=300

